const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.List,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.filechooser,
		C3.Plugins.BinaryData,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.List.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.List.Acts.SetInstanceVar,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Spritefont2.Acts.SetEffectParam,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.TextBox.Exps.Text,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.filechooser.Cnds.HasTags,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.Json.Acts.SetNull,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.filechooser.Acts.ChangeTags,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.AJAX.Cnds.OnAnyComplete,
		C3.Plugins.AJAX.Cnds.OnAnyError
	];
};
self.C3_JsPropNameTable = [
	{item: 0},
	{List: 0},
	{SpriteFont: 0},
	{SpriteFont2: 0},
	{jamKredit: 0},
	{mataNilaian: 0},
	{jumlahMataNilaianGred: 0},
	{totalMataNilaian: 0},
	{Catatan: 0},
	{PNG: 0},
	{noMatrik: 0},
	{semester: 0},
	{gred: 0},
	{namaKursus: 0},
	{itemm: 0},
	{Tween: 0},
	{SpriteFont3: 0},
	{jamKreditGet: 0},
	{ListGred: 0},
	{questionButton: 0},
	{bg: 0},
	{infoPNG: 0},
	{Touch: 0},
	{hitam: 0},
	{data: 0},
	{off: 0},
	{buttonBG: 0},
	{backButton: 0},
	{Sine: 0},
	{hiasan: 0},
	{Struktur2: 0},
	{item2: 0},
	{TextInput: 0},
	{ListCurrentSemester: 0},
	{nextButton: 0},
	{LocalStorage: 0},
	{click: 0},
	{deleteSaveData: 0},
	{AJAX: 0},
	{SettingBtn: 0},
	{PrintBtn: 0},
	{ListKategori: 0},
	{GambarDapat: 0},
	{JSON: 0},
	{FileChooser: 0},
	{BinaryData: 0},
	{JSONToSend: 0},
	{GambarDapat2: 0},
	{GambarDapat3: 0},
	{GambarDapat4: 0},
	{GambarDapat5: 0},
	{targetx: 0},
	{targety: 0},
	{ScrollTo: 0},
	{camera: 0},
	{JSONAdminData: 0},
	{JSONTemp: 0},
	{JSONTempInside: 0},
	{Bulat: 0},
	{Flash: 0},
	{notification: 0},
	{Sprite: 0},
	{namaSubjek: 0},
	{JSONsylabus: 0},
	{creditSubjek: 0},
	{gredSubjek: 0},
	{mataNilaianGred: 0},
	{PrintNamaKursus1: 0},
	{PrintGred1: 0},
	{PrintJamKredit1: 0},
	{PrintMataNilaian1: 0},
	{PrintJumlah1: 0},
	{PrintNamaKursus2: 0},
	{PrintGred2: 0},
	{PrintJamKredit2: 0},
	{PrintMataNilaian2: 0},
	{PrintJumlah2: 0},
	{PrintNamaKursus3: 0},
	{PrintGred3: 0},
	{PrintJamKredit3: 0},
	{PrintMataNilaian3: 0},
	{PrintJumlah3: 0},
	{PrintJumlahGred1: 0},
	{PrintPNG1: 0},
	{PrintJumlahGred2: 0},
	{PrintPNG2: 0},
	{PrintJumlahGred3: 0},
	{PrintPNG3: 0},
	{HantarData: 0},
	{total: 0},
	{jumlahTimbunanMNG: 0},
	{jumlahCreditSubjek: 0},
	{png: 0},
	{datatosend: 0},
	{PrintNamaKursuss: 0},
	{PrintGreds: 0},
	{PrintJamKredits: 0},
	{PrintMataNilaians: 0},
	{PrintJumlahs: 0},
	{numSem: 0},
	{keputusanSem: 0},
	{SaveID: 0},
	{SaveID_Print: 0},
	{username: 0},
	{password: 0},
	{buttonbulat: 0},
	{temp: 0},
	{saveKejapUntukSave: 0},
	{typeUser: 0},
	{frame: 0},
	{queryString: 0},
	{tag: 0},
	{counter: 0},
	{strukturinarray: 0},
	{password_student: 0},
	{kategori: 0},
	{tempVariable: 0},
	{semesterKeputusan1: 0},
	{semesterKeputusan2: 0},
	{semesterKeputusan3: 0},
	{semesterKeputusan1Get: 0},
	{semesterKeputusan2Get: 0},
	{semesterKeputusan3Get: 0},
	{fromPage: 0},
	{JSONDataUser: 0},
	{TEMPTEST: 0},
	{Database: 0},
	{keputusan: 0},
	{keyToGet: 0},
	{datagett: 0},
	{QUERY2: 0},
	{IMAGE1: 0},
	{IMAGE2: 0},
	{IMAGE3: 0},
	{IMAGE4: 0},
	{IMAGE5: 0},
	{DEFAULTIMAGE: 0},
	{LINKAPI: 0},
	{LINKAPI2: 0},
	{APIDATA: 0},
	{ISSTUDENT: 0},
	{QUERY: 0},
	{ALLQUERY: 0},
	{pageStruktur: 0},
	{stemtype: 0},
	{stemtypeIndex: 0},
	{mentor: 0},
	{mentorIndex: 0},
	{namaPelajar: 0},
	{printslippage: 0},
	{page: 0}
];

self.InstanceType = {
	List: class extends self.IListInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	ListGred: class extends self.IListInstance {},
	questionButton: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	infoPNG: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	hitam: class extends self.ITiledBackgroundInstance {},
	buttonBG: class extends self.ISpriteInstance {},
	backButton: class extends self.ISpriteInstance {},
	hiasan: class extends self.ISpriteInstance {},
	Struktur2: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	ListCurrentSemester: class extends self.IListInstance {},
	nextButton: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	deleteSaveData: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	SettingBtn: class extends self.ISpriteInstance {},
	PrintBtn: class extends self.ISpriteInstance {},
	ListKategori: class extends self.IListInstance {},
	GambarDapat: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	FileChooser: class extends self.IFileChooserInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	JSONToSend: class extends self.IJSONInstance {},
	GambarDapat2: class extends self.ISpriteInstance {},
	GambarDapat3: class extends self.ISpriteInstance {},
	GambarDapat4: class extends self.ISpriteInstance {},
	GambarDapat5: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	JSONAdminData: class extends self.IJSONInstance {},
	JSONTemp: class extends self.IJSONInstance {},
	JSONTempInside: class extends self.IJSONInstance {},
	Bulat: class extends self.ISpriteInstance {},
	notification: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {}
}